Check OS before run protractor

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -1,17 +1,17 @@
+---
 format_version: 1.3.1
 default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
 app:
   envs:
-  - IONIC_PROJ_DIR_PATH: ./handup
-  # for iOS
-  - BITRISE_PROJECT_PATH: ./platforms/ios/handup.xcodeproj
+  - IONIC_PROJ_DIR_PATH: "./handup"
+  - BITRISE_PROJECT_PATH: "./platforms/ios/handup.xcodeproj"
   - BITRISE_SCHEME: handup
   - FORCE_TEAM_ID: 6DLEBYX6Q8
 trigger_map:
 - push_branch: master
-  workflow: ci-android
+  workflow: ci-ios
 - pull_request_source_branch: "*"
-  workflow: ci-android
+  workflow: ci-ios
 workflows:
   _ci_finish:
     steps:
@@ -22,6 +22,8 @@ workflows:
     - activate-ssh-key@3.1.1:
         run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
     - git-clone@3.4.1: {}
+  _ci_setup_android_tests:
+    steps:
     - script@1.1.3:
         title: Setup test env
         inputs:
@@ -41,17 +43,31 @@ workflows:
             chmod a+x /usr/bin/xvfb-chromium
 
             envman add --key CHROME_BIN --value "/usr/bin/xvfb-chromium"
-  build-android:
+          opts: {}
+  _ci_setup_ios_tests:
+    steps:
+    - script@1.1.3:
+        title: Setup test env
+        inputs:
+        - content: |-
+            #!/bin/bash
+            # fail if any commands fails
+            set -e
+
+            brew tap caskroom/cask
+            brew cask install google-chrome
+
+            echo $CHROME_BIN
+          opts: {}
+  test:
     steps:
     - change-workdir@1.0.1:
         title: Change workdir to ionic project dir
         inputs:
-        - opts: {}
-          path: $IONIC_PROJ_DIR_PATH
-        - is_create_path: "false"
-          opts: {}
+        - path: "$IONIC_PROJ_DIR_PATH"
+        - is_create_path: 'false'
     - script@1.1.3:
-        title: Build the app for distribution
+        title: Test the app
         inputs:
         - content: |-
             #!/bin/bash
@@ -63,17 +79,22 @@ workflows:
             mkdir -p www
 
             npm run test:all
+          opts: {}
+  build-android:
+    steps:
+    - script@1.1.3:
+        title: Build the app for distribution
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -ex
+            #
             ionic platform add android
             ionic build android --prod
             mv ./platforms/android/build/outputs/apk/android-debug.apk "${BITRISE_DEPLOY_DIR}"
           opts: {}
   build-ios:
     steps:
-    - change-workdir@1.0.1:
-        title: Change workdir to ionic project dir
-        inputs:
-        - path: $IONIC_PROJ_DIR_PATH
-        - is_create_path: "false"
     - script@1.1.3:
         title: Build the app for distribution
         inputs:
@@ -81,32 +102,30 @@ workflows:
             #!/bin/bash
             set -ex
             #
-            npm install
-            node ./node_modules/protractor/bin/webdriver-manager update
-
-            mkdir -p www
-
-            npm run test:all
             ionic platform add ios
             ionic build ios --prod
             mv ./platforms/android/build/outputs/apk/android-debug.apk "${BITRISE_DEPLOY_DIR}"
     - recreate-user-schemes:
         inputs:
-        - project_path: $BITRISE_PROJECT_PATH
+        - project_path: "$BITRISE_PROJECT_PATH"
     - certificate-and-profile-installer@1.8.2: {}
     - xcode-archive@2.0.4:
         inputs:
-        - force_team_id: $FORCE_TEAM_ID
+        - force_team_id: "$FORCE_TEAM_ID"
         - force_code_sign_identity: iPhone Developer
-  ci-ios:
-    before_run:
-    - _ci_setup
-    after_run:
-    - build-ios
-    - _ci_finish
   ci-android:
     before_run:
     - _ci_setup
+    - _ci_setup_android_tests
     after_run:
+    - test
     - build-android
+    - _ci_finish
+  ci-ios:
+    before_run:
+    - _ci_setup
+    - _ci_setup_ios_tests
+    after_run:
+    - test
+    - build-ios
     - _ci_finish
