Install chrome from bitrise.yml

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -18,6 +18,24 @@ workflows:
         inputs:
         - content: |-
             #!/bin/bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+            
+            apt-get update && apt-get install -y  curl apt-transport-https
+            curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
+            echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
+            apt-get update && apt-get install -y dbus-x11 git xvfb google-chrome-stable curl --no-install-recommends
+            apt-get purge --auto-remove -y curl apt-transport-https
+            rm -rf /var/lib/apt/lists/*
+
+            cp xvfb-chromium /usr/bin/xvfb-chromium
+            # ADD xvfb-firefox /usr/bin/xvfb-firefox
+
+            chmod a+x /usr/bin/xvfb-chromium
+            # RUN chmod a+x /usr/bin/xvfb-firefox
+
             envman add --key CHROME_BIN --value "/usr/bin/xvfb-chromium"
           opts: {}
   build-android:
